import { type NextPage } from "next";
import Head from "next/head";
import AppFooter from "../components/AppFooter";
import AppHeader from "../components/AppHeader";
import Blog from "../components/Blog";
import CallToAction from "../components/CallToAction";
import Features from "../components/Features";
import HeroSection from "../components/HeroSection";
import Stats from "../components/Stats";
import Testimonials from "../components/Testimonials";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Tamu ThinkTank</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-white dark:bg-gray-900">
        <AppHeader />
        <main className="mb-40 space-y-40">
          <HeroSection />
          <Features />
          <Stats />
          <Testimonials />
          <CallToAction />
          <Blog />
        </main>
        <AppFooter />
      </body>
    </>
  );
};

export default Home;
